server:
  port: 8080
  shutdown: graceful

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: create

datasource:
  db:
    pool-name: accompany
    jdbc-url: jdbc:mysql://localhost:3306/accompany?useSSL=false&&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 5
    connection-timeout: 3000
    cache-prep-stmts: true
    prep-stmt-cache-size: 250
    prep-stmt-cache-sql-limit: 2048
    use-server-prep-stmts: true
    use-local-session-state: true
    cache-result-set-metadata: true
    maintain-time-stats: false
    leak-detection-threshold: 5000
    autocommit: false
    connection-init-sql: "SET NAMES 'utf8mb4'"
    read-only: false
    data-source-properties:
      useCursors: false
      sendStringParametersAsUnicode: false
      characterEncoding: utf8
      zeroDateTimeBehavior: convertToNull
      useSSL: false
      autoReconnect: true
      autoReconnectForPools: true
      usePipelineAuth: false
      useBatchMultiSend: false
